---
- name: Install Docker
  ansible.builtin.include_tasks:
    file: docker_install.yml
    apply:
      tags:
        - docker
  tags:
    - docker

- name: Install Checkpoint WAF Agent
  ansible.builtin.include_tasks:
    file: checkpoint_waf_agent_install.yml
    apply:
      tags:
        - checkpoint_waf_agent
  tags:
    - checkpoint_waf_agent
